import { ArrowRight, Braces, CalendarClock, FileClock, Files, FolderKanban, GitCompareArrows, ShieldCheck } from "lucide-react";
import type { ViewId, WorkspaceRecord } from "../types";
import { useAppStore } from "../store/appStore";
import { Badge, Button, EmptyState } from "../components/ui";
import { formatBytes, formatDateTime } from "../utils";
import { translate as t } from "../i18n";

export function HomePage({ onNavigate, onOpenWorkspace }: { onNavigate: (view: ViewId) => void; onOpenWorkspace: (workspace: WorkspaceRecord) => void }) {
  const workspaces = useAppStore((state) => state.workspaces);
  const recentFiles = useAppStore((state) => state.recentFiles);
  const cards = [
    { view: "format" as const, icon: <Braces />, title: t("格式化与校验"), text: t("JSON / JSONC / XML 自动识别、格式化、压缩、结构查看与问题定位。"), meta: "P0" },
    { view: "diff" as const, icon: <GitCompareArrows />, title: t("报文对比"), text: t("文本、语义、结构三种模式，支持数组策略、路径规则和可交付报告。"), meta: "P0" },
    { view: "cron" as const, icon: <CalendarClock />, title: t("Cron 生成与复原"), text: t("Unix、Spring、Quartz 方言，字段构造、中文解释和运行时间预览。"), meta: "P0" },
    { view: "batch" as const, icon: <Files />, title: t("批量对比"), text: t("选择左右目录，按相对路径自动配对并批量生成结果。"), meta: "P1" },
  ];
  return <div className="page-scroll home-page"><section className="home-hero"><div><Badge tone="accent">{t("API 对接工作台")}</Badge><h1>{t("把报文处理的零散步骤，集中到一个本地工具里。")}</h1><p>{t("格式化、校验、语义对比、Cron 复原、结果导出和工作区复用。默认只在本机处理，不上传报文。")}</p><div className="hero-actions"><Button variant="primary" onClick={() => onNavigate("diff")}><GitCompareArrows />{t("开始对比")}</Button><Button onClick={() => onNavigate("format")}><Braces />{t("整理报文")}</Button></div></div><aside><ShieldCheck /><strong>Local first</strong><span>{t("敏感报文留在当前设备")}</span><span>{t("Web 与 Windows 使用同一套能力")}</span></aside></section><section className="home-columns"><div><div className="section-heading compact"><div><span className="eyebrow">{t("继续工作")}</span><h2>{t("最近工作区")}</h2></div><button className="text-action" onClick={() => onNavigate("workspaces")}>{t("全部工作区")}</button></div><div className="list-card">{workspaces.length ? workspaces.slice(0, 5).map((workspace) => <button className="recent-row" key={workspace.id} onClick={() => onOpenWorkspace(workspace)}><span className="recent-icon"><FolderKanban /></span><span className="recent-main"><strong>{workspace.name}</strong><small>{workspace.type.toUpperCase()} · {formatDateTime(workspace.updatedAt)}</small></span>{workspace.pinned && <Badge tone="warning">{t("已置顶")}</Badge>}<ArrowRight /></button>) : <EmptyState icon={<FolderKanban />} title={t("还没有保存的工作区")} description={t("在任一工具中点击“保存工作区”，即可在这里继续。")} />}</div></div><div><div className="section-heading compact"><div><span className="eyebrow">{t("本机记录")}</span><h2>{t("最近文件")}</h2></div></div><div className="list-card">{recentFiles.length ? recentFiles.slice(0, 5).map((file) => <div className="recent-row static" key={file.id}><span className="recent-icon"><FileClock /></span><span className="recent-main"><strong>{file.name}</strong><small>{file.format.toUpperCase()} · {formatBytes(file.size)}</small></span></div>) : <EmptyState icon={<FileClock />} title={t("暂无最近文件")} description={t("打开本地报文后，这里会显示文件名和大小，不保存报文内容。")} />}</div></div></section><section><div className="section-heading"><div><span className="eyebrow">{t("快速开始")}</span><h2>{t("常用工具")}</h2></div><span>{t("无需创建项目，打开即用")}</span></div><div className="tool-card-grid">{cards.map((card) => <button className="tool-card" key={card.view} onClick={() => onNavigate(card.view)}><div className="tool-card-icon">{card.icon}</div><Badge tone={card.meta === "P0" ? "success" : "accent"}>{card.meta}</Badge><h3>{card.title}</h3><p>{card.text}</p><span className="card-link">{t("打开工具")} <ArrowRight /></span></button>)}</div></section></div>;
}
