export const SQL_KEYWORDS = [
  "ADD", "ALL", "ALTER", "AND", "ANY", "AS", "ASC", "BEGIN", "BETWEEN", "BY", "CALL", "CASE", "CHECK", "COLUMN", "COMMIT",
  "CONSTRAINT", "CREATE", "CROSS", "CURRENT", "DATABASE", "DECLARE", "DEFAULT", "DELETE", "DESC", "DESCRIBE", "DISTINCT", "DROP", "ELSE",
  "END", "EXEC", "EXECUTE", "EXISTS", "EXPLAIN", "FALSE", "FETCH", "FOR", "FOREIGN", "FROM", "FULL", "FUNCTION", "GRANT", "GROUP", "HAVING",
  "IN", "INDEX", "INNER", "INSERT", "INTERSECT", "INTO", "IS", "JOIN", "KEY", "LEFT", "LIKE", "LIMIT", "MERGE", "NOT", "NULL", "OFFSET",
  "ON", "OR", "ORDER", "OUTER", "PRIMARY", "PROCEDURE", "REFERENCES", "REPLACE", "RETURNING", "REVOKE", "RIGHT", "ROLLBACK", "SELECT", "SET",
  "SHOW", "TABLE", "THEN", "TOP", "TRANSACTION", "TRUNCATE", "TRUE", "UNION", "UNIQUE", "UPDATE", "USE", "USING", "VALUES", "VIEW", "WHEN",
  "WHERE", "WITH",
] as const;
